apiVersion: v1
kind: Secret
metadata:
  name: player-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  PLAYER_EMAIL: {{ .Values.player.email | quote }}
  PLAYER_PASSWORD: {{ .Values.player.password | quote }}
