apiVersion: v1
kind: Secret
metadata:
  name: mercadopago-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  MERCADOPAGO_ACCESS_TOKEN: {{ .Values.mercadoPago.accessToken | quote }}
  MERCADOPAGO_WEBHOOK_SECRET: {{ .Values.mercadoPago.webhookSecret | quote }}
