apiVersion: v1
kind: Secret
metadata:
  name: abacatepay-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  ABACATEPAY_API_KEY: {{ .Values.abacatePay.apiKey | quote }}
  ABACATEPAY_WEBHOOK_SECRET: {{ .Values.abacatePay.webhookSecret | quote }}
