apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.rabbitmq.username | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.rabbitmq.password | quote }}
