apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgres.superuserPassword | quote }}
  {{- range $key, $role := .Values.postgres.roles }}
  {{ $key | upper }}_DB_PASSWORD: {{ $role.password | quote }}
  {{- end }}
